import { fileURLToPath } from "node:url";
import { readFile, readdir } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const IMAGES_DIR = path.join(ROOT, "public", "images");
const MANIFEST = path.join(ROOT, "src", "data", "image-manifest.json");

function titleCase(str) {
  return str
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

async function loadManifest() {
  try {
    return JSON.parse(await readFile(MANIFEST, "utf8"));
  } catch {
    return {};
  }
}

async function localImagePaths() {
  const out = [];
  let entries = [];
  try {
    entries = await readdir(IMAGES_DIR, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const cat of entries) {
    if (!cat.isDirectory() || cat.name.startsWith(".")) continue;
    let subEntries = [];
    try {
      subEntries = await readdir(path.join(IMAGES_DIR, cat.name), { withFileTypes: true });
    } catch {
      continue;
    }
    for (const proj of subEntries) {
      if (!proj.isDirectory() || proj.name.startsWith(".")) continue;
      const ref = `/images/${slug(cat.name)}/${slug(proj.name)}`;
      for (const file of await readdir(path.join(IMAGES_DIR, cat.name, proj.name))) {
        if (!/\.(jpe?g|png|webp|heic)$/i.test(file) || file.startsWith(".")) continue;
        out.push({ ref: `${ref}/${file}`, display: `${cat.name}/${proj.name}/${file}` });
      }
    }
  }
  return out;
}

function slug(str) {
  return str
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

async function report() {
  const manifest = await loadManifest();
  const keys = Object.keys(manifest);
  console.log(`[lumen] ${keys.length} indexed photo(s) in ${path.relative(ROOT, MANIFEST)}`);

  const perCat = new Map();
  const perProject = new Map();
  for (const src of keys) {
    const info = manifest[src];
    const cat = info.category ?? src.split("/")[2];
    const proj = info.project ?? src.split("/")[3];
    perCat.set(cat, (perCat.get(cat) ?? 0) + 1);
    perProject.set(`${cat}/${proj}`, (perProject.get(`${cat}/${proj}`) ?? 0) + 1);
  }

  const cats = [...perCat.keys()].sort((a, b) => a.localeCompare(b));
  for (const cat of cats) {
    console.log(`\n  ${titleCase(cat)} (${perCat.get(cat)})`);
    for (const [proj, n] of [...perProject.entries()].filter(([p]) => p.startsWith(`${cat}/`)).sort()) {
      console.log(`    ${titleCase(proj.split("/").pop())}  ${n}`);
    }
  }

  const indexed = new Set(keys);
  const local = await localImagePaths();
  const unindexed = local.filter((l) => !indexed.has(l.ref));
  if (unindexed.length) {
    console.log(`\n[unindexed] ${unindexed.length} photo(s) on disk not in the manifest:`);
    for (const u of unindexed.slice(0, 15)) console.log(`  ${u.display}`);
    if (unindexed.length > 15) console.log(`  …and ${unindexed.length - 15} more`);
    console.log("  Run `npm run uploads:portfolio` to upload + re-index them.");
  }

  const byName = new Map();
  for (const src of keys) {
    const file = src.split("/").pop();
    if (!byName.has(file)) byName.set(file, []);
    byName.get(file).push(src.replace(/^\/images\//, "").replace(/\.[a-z0-9]+$/i, ""));
  }
  const dupes = [...byName.entries()].filter(([, v]) => v.length > 1);
  if (dupes.length) {
    console.log(`\n[dupe] ${dupes.length} filename(s) appear in multiple projects (usually edits):`);
    for (const [file, where] of dupes.slice(0, 15)) console.log(`  ${file} -> ${where.join(", ")}`);
    if (dupes.length > 15) console.log(`  …and ${dupes.length - 15} more`);
  }
}

const usage = `Usage: node scripts/lumen.mjs <report>
  report    Audit the image manifest: counts per category/project, unindexed
            local photos, and duplicate filenames.

  The manifest is generated by "npm run uploads:portfolio" (see scripts/r2-upload.mjs).`;

async function main() {
  const [command] = process.argv.slice(2);
  if (command === "report") {
    await report();
    return;
  }
  if (!command) {
    console.error(usage);
    process.exit(1);
  }
  console.error(usage);
  process.exit(1);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});