import sharp from 'sharp'
import { readdir, mkdir, stat, writeFile, readFile } from 'fs/promises'
import { join, extname } from 'path'

const BASE = './public/images'
const OUT = './public/images/optimized'
const MANIFEST = './src/data/imageManifest.mjs'

const CATEGORIES = ['favorite', 'street', 'portrait', 'architecture', 'summer-picnic', 'film', 'all']
const WIDTHS = [640, 1200, 1600]
const JPEG_QUALITY = 80
const WEBP_QUALITY = 72
const BLUR_SIZE = 16

const urlOf = (p) => p.replace(/^\.?\/?public/, '').replace(/\\/g, '/')
const IMAGE_EXTS = ['.jpg', '.jpeg', '.png', '.webp']

const done = []
const skipped = []

async function listImages(dir) {
  const entries = await readdir(dir)
  const files = []
  for (const name of entries) {
    if (IMAGE_EXTS.includes(extname(name).toLowerCase())) files.push(name)
  }
  return files.sort()
}

function slugify(name) {
  return name.replace(/\.[^/.]+$/, '')
}

async function outputFresh(outPath, sourceMtime) {
  try {
    const st = await stat(outPath)
    return st.mtimeMs >= sourceMtime
  } catch {
    return false
  }
}

async function buildVariants(category, name) {
  const srcPath = join(BASE, category, name)
  const base = slugify(name)
  const outDir = join(OUT, category)
  await mkdir(outDir, { recursive: true })

  const { mtimeMs } = await stat(srcPath)
  const outputs = [
    ...WIDTHS.map((w) => join(outDir, `${base}@${w}w.webp`)),
    join(outDir, `${base}@1600w.jpg`),
  ]
  const fresh = (await Promise.all(outputs.map((f) => outputFresh(f, mtimeMs)))).every(Boolean)

  const meta = await sharp(srcPath).metadata()
  const width = meta.width
  const height = meta.height

  if (fresh && !process.env.FORCE_IMAGES) {
    skipped.push(`${category}/${name}`)
    let placeholder = ''
    try {
      placeholder = (await readFile(join(outDir, `${base}.blur`))).toString('base64')
    } catch {}
    return {
      skipped: true,
      width,
      height,
      webp: WIDTHS.map((w) => `${urlOf(join(outDir, `${base}@${w}w.webp`))} ${w}w`),
      jpeg: [`${urlOf(join(outDir, `${base}@1600w.jpg`))} 1600w`],
      placeholder,
    }
  }

  const image = sharp(srcPath).rotate()

  const variants = { webp: [], jpeg: [] }
  for (const w of WIDTHS) {
    const resized = image.clone().resize({ width: w, withoutEnlargement: true })
    const webpPath = join(outDir, `${base}@${w}w.webp`)
    await resized.clone().webp({ quality: WEBP_QUALITY }).toFile(webpPath)
    variants.webp.push(`${urlOf(webpPath)} ${w}w`)
  }

  const jpg1600 = join(outDir, `${base}@1600w.jpg`)
  await image
    .clone()
    .resize({ width: 1600, withoutEnlargement: true })
    .flatten({ background: '#f0ebce' })
    .jpeg({ quality: JPEG_QUALITY, mozjpeg: true })
    .toFile(jpg1600)
  variants.jpeg.push(`${urlOf(jpg1600)} 1600w`)

  const placeholder = await image
    .clone()
    .resize({ width: BLUR_SIZE, withoutEnlargement: true })
    .webp({ quality: 30 })
    .toBuffer()

  await writeFile(join(outDir, `${base}.blur`), placeholder)

  done.push(`${category}/${name}`)
  return { skipped: false, width, height, webp: variants.webp, jpeg: variants.jpeg, placeholder }
}

async function main() {
  console.log('Optimizing images...')
  const manifest = {}

  const start = Date.now()
  for (const category of CATEGORIES) {
    const files = await listImages(join(BASE, category))
    const chunk = 4
    for (let i = 0; i < files.length; i += chunk) {
      await Promise.all(
        files.slice(i, i + chunk).map((name) => buildVariants(category, name).then((r) => {
          const key = `/images/${category}/${name}`
          manifest[key] = {
            src: `/images/optimized/${category}/${slugify(name)}@1600w.jpg`,
            webp: r.webp,
            jpeg: r.jpeg,
            placeholder: r.placeholder?.toString('base64') ?? '',
            width: r.width,
            height: r.height,
          }
        })),
      )
    }
  }

  const catalog = Object.fromEntries(
    Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)),
  )

  await mkdir('./src/data', { recursive: true })
  await writeFile(
    MANIFEST,
    `// AUTO-GENERATED by scripts/optimize.mjs — do not edit by hand.\nexport const imageCatalog = ${JSON.stringify(catalog, null, 2)}\n`,
  )

  const secs = ((Date.now() - start) / 1000).toFixed(1)
  console.log(`\n✓ optimized ${done.length} images ✓ skipped ${skipped.length}`)
  console.log(`Manifest: ${MANIFEST} (${Object.keys(catalog).length} entries) — ${secs}s`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})