import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { readFile, readdir, mkdir, writeFile } from "node:fs/promises";
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";
import {
  r2OriginalKey,
  r2PreviewKey,
  signedPutHeaders,
} from "../lib/r2-sign.ts";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const envPath = path.join(ROOT, ".env.local");
try {
  const raw = await readFile(envPath, "utf8");
  for (const line of raw.split("\n")) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (m && !(m[1] in process.env)) process.env[m[1]] = m[2].replace(/^["']|["']$/g, "");
  }
} catch {
  // env vars may already be exported
}

const cfg = {
  accountId: process.env.R2_ACCOUNT_ID ?? "",
  accessKeyId: process.env.R2_ACCESS_KEY_ID ?? "",
  secretAccessKey: process.env.R2_SECRET_ACCESS_KEY ?? "",
  bucket: process.env.R2_BUCKET ?? "",
};
if (!cfg.accountId || !cfg.accessKeyId || !cfg.secretAccessKey || !cfg.bucket) {
  console.error("[r2] R2 credentials are incomplete in .env.local");
  process.exit(1);
}

const usage = `Usage: node scripts/r2-upload.mjs <slug> [sourceDir]
  Uploads full-res originals + webp previews of every image in sourceDir to
  Cloudflare R2 as gallery/<slug>/<file>, then writes
  content/galleries/<slug>/gallery.json with an auto-generated
  branded password (LUMEN-<hex>) and a cover pointing at the first upload.

  Re-running for an existing gallery keeps its current password and settings.`;

const slug = process.argv[2];
const sourceDir = process.argv[3] ?? path.join(ROOT, "deliverables", slug);
if (!slug || !fs.existsSync(sourceDir)) {
  console.error(usage);
  process.exit(1);
}

const generatePassword = () =>
  `LUMEN-${randomBytes(5).toString("hex").toUpperCase()}`;

const PASSWORDS_FILE = path.join(ROOT, "deliverables", "passwords.html");

const esc = (s) =>
  String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const unesc = (s) =>
  String(s ?? "")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");

const renderPasswordsPage = (rows) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>THE.LUMENCODE — Gallery Passwords</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    background: #16120e;
    color: #e9e2d6;
    font: 15px/1.5 ui-monospace, "SF Mono", Menlo, Consolas, monospace;
  }
  main { max-width: 880px; margin: 0 auto; padding: 56px 24px 64px; }
  header { border-bottom: 1px solid rgba(201,169,126,0.25); padding-bottom: 20px; margin-bottom: 24px; }
  header h1 { margin: 0; font-size: 22px; letter-spacing: 0.24em; color: #c9a97e; }
  header p { margin: 8px 0 0; text-transform: uppercase; letter-spacing: 0.18em; font-size: 11px; color: #8a8378; }
  .note { font-size: 12px; color: #8a8378; margin: 0 0 28px; }
  table { width: 100%; border-collapse: collapse; background: #211b15; border: 1px solid rgba(201,169,126,0.15); border-radius: 14px; overflow: hidden; }
  th, td { text-align: left; padding: 14px 18px; }
  thead th { text-transform: uppercase; letter-spacing: 0.12em; font-size: 11px; color: #a89d8c; background: rgba(201,169,126,0.08); }
  tbody tr + tr { border-top: 1px solid rgba(201,169,126,0.1); }
  td.pw { color: #d9b98a; font-weight: 700; letter-spacing: 0.06em; }
  td.dim, .empty { color: #8a8378; }
  .empty { font-size: 13px; border: 1px solid rgba(201,169,126,0.15); background: #211b15; border-radius: 14px; padding: 32px; text-align: center; }
  footer { margin-top: 28px; font-size: 11px; color: #6f6a60; text-transform: uppercase; letter-spacing: 0.14em; }
</style>
</head>
<body>
<main>
  <header>
    <h1>THE.LUMENCODE</h1>
    <p>Delivery gallery passwords</p>
  </header>
  <p class="note">Keep this file private — it is git-ignored and never deployed.</p>
  ${
    rows.length
      ? `<table>
  <thead><tr><th>Gallery</th><th>Password</th><th>Title</th><th>Date</th></tr></thead>
  <tbody>
${rows
  .map(
    (r) =>
      `<tr data-slug="${esc(r.slug)}"><td>${esc(r.slug)}</td><td class="pw">${esc(r.password)}</td><td>${esc(r.title)}</td><td class="dim">${esc(r.date)}</td></tr>`,
  )
  .join("\n")}
  </tbody>
</table>`
      : '<p class="empty">No galleries yet.</p>'
  }
  <footer>Generated by scripts/r2-upload.mjs</footer>
</main>
</body>
</html>
`;

async function upsertPasswordFile({ slug, password, title, date }) {
  let rows = [];
  try {
    const html = await readFile(PASSWORDS_FILE, "utf8");
    const rowRe = /<tr data-slug="([^"]+)"([\s\S]*?)<\/tr>/g;
    let m;
    while ((m = rowRe.exec(html))) {
      const cells = [...m[2].matchAll(/<td class="([^"]*)"?>([\s\S]*?)<\/td>/g)].map(
        (c) => unesc(c[2]),
      );
      rows.push({ slug: m[1], password: cells[1] ?? "", title: cells[2] ?? "", date: cells[3] ?? "" });
    }
  } catch {
    // file not created yet
  }
  rows = rows.filter((r) => r.slug !== slug);
  rows.push({ slug, password, title: title ?? "", date: date ?? "" });
  rows.sort((a, b) => a.slug.localeCompare(b.slug));
  await writeFile(PASSWORDS_FILE, renderPasswordsPage(rows));
}

const mime = (f) => {
  const ext = path.extname(f).toLowerCase();
  return ext === ".png" ? "image/png" : ext === ".webp" ? "image/webp" : ext === ".heic" ? "image/heic" : "image/jpeg";
};

async function put(key, body, contentType) {
  const headers = await signedPutHeaders(cfg, key, body, contentType);
  const path = key.split("/").map(encodeURIComponent).join("/");
  const res = await fetch(`https://${cfg.accountId}.r2.cloudflarestorage.com/${cfg.bucket}/${path}`, {
    method: "PUT",
    headers,
    body,
  });
  if (!res.ok) throw new Error(`PUT ${key} -> ${res.status} ${await res.text().catch(() => "")}`);
}

async function main() {
  const files = (await readdir(sourceDir))
    .filter((f) => /\.(jpe?g|png|webp|heic)$/i.test(f) && !f.startsWith("."))
    .sort();

  if (!files.length) {
    console.error(`[r2] no image files in ${sourceDir}`);
    process.exit(1);
  }

  const manifest = [];
  for (const file of files) {
    const originalKey = r2OriginalKey(slug, file);
    const previewKey = r2PreviewKey(slug, file);
    const body = await readFile(path.join(sourceDir, file));
    await put(originalKey, body, mime(file));
    const preview = await sharp(body).rotate().resize({ width: 1600, withoutEnlargement: true }).webp({ quality: 80 }).toBuffer();
    await put(previewKey, preview, "image/webp");
    manifest.push({ name: file, src: `r2:${originalKey}` });
    console.log(`  ${file} -> ${originalKey}`);
  }

  const outDir = path.join(ROOT, "content", "galleries", slug);
  await mkdir(outDir, { recursive: true });

  let existing = {};
  try {
    existing = JSON.parse(await readFile(path.join(outDir, "gallery.json"), "utf8"));
  } catch {
    // first upload for this gallery
  }

  const password = existing.password || generatePassword();
  const gallery = {
    title: existing.title ?? slug,
    slug,
    cover: manifest[0].src,
    description: existing.description,
    password,
    download: existing.download ?? false,
    featured: existing.featured ?? false,
    category: existing.category ?? "portrait",
    location: existing.location,
    date: existing.date,
    expires: existing.expires,
    images: manifest.map((m) => m.src),
  };

  await writeFile(path.join(outDir, "r2-manifest.json"), JSON.stringify(manifest, null, 2) + "\n");
  await writeFile(path.join(outDir, "gallery.json"), JSON.stringify(gallery, null, 2) + "\n");
  await upsertPasswordFile({
    slug,
    password,
    title: gallery.title,
    date: gallery.date,
  });
  console.log(`[r2] uploaded ${files.length} original + ${files.length} preview; wrote content/galleries/${slug}/gallery.json`);
  console.log(`[r2] gallery password -> ${password} (saved to deliverables/passwords.html)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});